### ISSUE TITLE
There is no data to run the code

### ISSUE THREAD

**Issue by rzhangpku** [AtmaHou/Seq2SeqDataAugmentationForLU#1]
There is no data to run the code. The source ATIS data "atis.fold0.pkl" or "atis.fold0.pkl.gz" cannot run the code. And what is the required data format?

**Comment by AtmaHou** [comment]
I am sorry to have just seen the issue here, the data has been sent to you, please feel free to ask me any questions.

**Comment by rzhangpku** [comment]
Yes, I have received the data. Thank you very much. You are very nice.

**Comment by tangtangsiqi** [comment]
could you please send me the data as well?? waiting for your quick reply~~~

**Comment by AtmaHou** [comment]
@tangtangsiqi Hi, we use conll format ATIS slot filling data, which is easy to cook~ 

Leave an email to me, then I'll send you~
:)

**Comment by tangtangsiqi** [comment]
thank you so much~~

**Comment by iamagarwalsumit** [comment]
@AtmaHou Can you please send the data for the code?

**Comment by AtmaHou** [comment]
> @AtmaHou Can you please send the data for the code?

Sent~

**Comment by iamagarwalsumit** [comment]
Thanks for such a prompt reply :)

**Comment by paul-you** [comment]
@AtmaHou can you please send me the data as well ?

**Comment by AtmaHou** [comment]
> @AtmaHou can you please send me the data as well ?

Give me the email?

**Comment by AtmaHou** [comment]
> @AtmaHou can you please send me the data as well ?

Sent.

**Comment by zhou1xiang2** [comment]
Could you please send me the data as well ? Thanks a lot

**Comment by ghost** [comment]
Could you please send me the data as well ? Thanks a lot.

**Comment by AtmaHou** [comment]
> Could you please send me the data as well ? Thanks a lot.

Sent~~

**Comment by cheesezh** [comment]
大神好，方便把数据也发我一份吗？cheesezh@qq.com

**Comment by AtmaHou** [comment]
> 大神好，方便把数据也发我一份吗？[cheesezh@qq.com](mailto:cheesezh@qq.com)

Sent~~ :)

**Comment by nirmalmedicare** [comment]
Any way I can get the data?

**Comment by AtmaHou** [comment]
> Any way I can get the data?

The data has already been included in the repo~~
https://github.com/AtmaHou/Seq2SeqDataAugmentationForLU/tree/master/Data
