### ISSUE TITLE
some questions about generation model

### ISSUE THREAD

**Issue by xugege0523** [AtmaHou/Seq2SeqDataAugmentationForLU#2]

**Comment by xugege0523** [comment]
这篇论文的目的是在小数据集上做数据增广但是：
1.在训练seq2seq的生成模型时，您用了多少条数据？论文里好像没有说清楚，如果用了atis的所有数据训练出的生成模型来生成数据做增广的话，是否有些矛盾呢？
  小弟才疏学浅，有些不太理解，希望作者帮助我理解一下，多谢🙏！

**Comment by AtmaHou** [comment]
您好，相关内容在论文Dataset部分第一二段。

我们为了模拟数据不足的情况，依照Chen et al. 把ATIS数据划分出小、中两个子集，具体数量可以在论文里看到。同时Stanford的数据每个上domain我们也只用了500句的子集标注并测试。

**Comment by xugege0523** [comment]
非常感谢！
还有一个问题，atis的数据集我已经有了，不知道具体在此项目里的格式是什么样子的呢？

**Comment by AtmaHou** [comment]
我们使用CONLL格式数据~形如：
Word\tLabel1
Word\tLabel1
Word\tLabel1

Word\tLabel1
Word\tLabel1

**Comment by xugege0523** [comment]
实在不好意思问您问题了，数据集的处理上我还是有些问题，能上传一份您用的数据集吗？多谢！想要复现一下您的结果，做一下对比；
再次感谢！

**Comment by AtmaHou** [comment]
好的啊~发你邮件吧，给我一个你的邮箱

**Comment by xugege0523** [comment]
493887691@qq.com
多谢！

**Comment by AtmaHou** [comment]
已发~

**Comment by xugege0523** [comment]
您好，还有一个问题，这个代码的环境是什么呀？第三步总是跑不通。
还有模式是选intent-slot还是leak-gan？
多谢多谢

**Comment by AtmaHou** [comment]
1. 主要环境：python3，pytorch 0.3
2. 正常应该是intent-slot，这个是按什么标准聚类的意思。有关gan的部分都忽略就好

**Comment by xugege0523** [comment]
您好，我的环境：python3.5，pytorch 0.3.1，模式为intent-slot；
但是在第三步python3 run_onmt_generation.py -t atis_labeled -f
还是遇到了问题，报错如下：
b'Preparing training ...\n'
b'Building Training...\n'
b'Building Vocab...\n'
b'Building Valid...\n'
b'Saving train/valid/fields\n'
b'Traceback (most recent call last):\n'
b'  File "./OpenNMT/preprocess.py", line 94, in <module>\n'
b'    main()\n'
b'  File "./OpenNMT/preprocess.py", line 89, in main\n'
b"    torch.save(train, open(opt.save_data + '.train.pt', 'wb'))\n"
b'  File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 135, in save\n'
b'    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))\n'
b'  File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 117, in _with_file_like\n'
b'    return body(f)\n'
b'  File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 135, in <lambda>\n'
b'    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))\n'
b'  File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 198, in _save\n'
b'    pickler.dump(obj)\n'
b"AttributeError: Can't pickle local object 'ONMTDataset.__init__.<locals>.filter_pred'\n"
Traceback (most recent call last):
  File "run_onmt_generation.py", line 278, in <module>
    main()
  File "run_onmt_generation.py", line 268, in main
    call_onmt('prepare_data' + TASK_NAME + cluster_method + str(split_rate) + pair_mod_str + no_index_str + no_filtering_str, param_config['prepare_data'])
  File "run_onmt_generation.py", line 225, in call_onmt
    raise RuntimeError
RuntimeError

本来不想麻烦您的，但是确实三天没有解决了；多谢！

**Comment by AtmaHou** [comment]
具体原因我也不太清楚，但至少看那个你的log信息中，你的子进程是python3.6的环境。然后这个bug是出在pickle的，跟主体代码貌似没有关系，你再调整一下环境的问题吧。
另外，如果还是不行的话，反正你已经把seq2seq的数据生成了，接下来你自己可以自己用openNMT或者别的Seq2Seq模型训练增广，然后简单写一些代码做接下来的工作，其实也比较容易了~

**Comment by saldfj1921** [comment]
> 您好，我的环境：python3.5，pytorch 0.3.1，模式为intent-slot；
> 但是在第三步python3 run_onmt_generation.py -t atis_labeled -f
> 还是遇到了问题，报错如下：
> b'Preparing training ...\n'
> b'Building Training...\n'
> b'Building Vocab...\n'
> b'Building Valid...\n'
> b'Saving train/valid/fields\n'
> b'Traceback (most recent call last):\n'
> b' File "./OpenNMT/preprocess.py", line 94, in \n'
> b' main()\n'
> b' File "./OpenNMT/preprocess.py", line 89, in main\n'
> b" torch.save(train, open(opt.save_data + '.train.pt', 'wb'))\n"
> b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 135, in save\n'
> b' return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))\n'
> b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 117, in _with_file_like\n'
> b' return body(f)\n'
> b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 135, in \n'
> b' return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))\n'
> b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 198, in _save\n'
> b' pickler.dump(obj)\n'
> b"AttributeError: Can't pickle local object 'ONMTDataset.**init**..filter_pred'\n"
> Traceback (most recent call last):
> File "run_onmt_generation.py", line 278, in 
> main()
> File "run_onmt_generation.py", line 268, in main
> call_onmt('prepare_data' + TASK_NAME + cluster_method + str(split_rate) + pair_mod_str + no_index_str + no_filtering_str, param_config['prepare_data'])
> File "run_onmt_generation.py", line 225, in call_onmt
> raise RuntimeError
> RuntimeError
> 
> 本来不想麻烦您的，但是确实三天没有解决了；多谢！

想问问你后来解决了么，我也是这个问题总是跑不通...

**Comment by bobobe** [comment]
能也发我一份数据吗，谢谢! @AtmaHou 邮箱420097885@qq.com

**Comment by AtmaHou** [comment]
1. 数据已发。
2. 关于前面提到的运行错误的问题，之前的人的erro log显示他在实际运行的时候用的3.6， 且这个bug主要是pickle里面的。我的建议检查一下你的python环境。

**Comment by bobobe** [comment]
> 
> 
>     1. 数据已发。
> 
>     2. 关于前面提到的运行错误的问题，之前的人的erro log显示他在实际运行的时候用的3.6， 且这个bug主要是pickle里面的。我的建议检查一下你的python环境。

收到，谢谢

**Comment by bobobe** [comment]
打扰一下，这个代码在windows下能跑通吗，您试过没有？我总是卡在第三步。

**Comment by qichaotang** [comment]
能发我一份数据吗，谢谢! @AtmaHou qichaotang97@163.com

**Comment by AtmaHou** [comment]
数据已发~

**Comment by qichaotang** [comment]
> 数据已发~

Thanks

**Comment by bobobe** [comment]
你好，你的torchtext和pytorch具体是什么版本？我环境为pytorch0.3.1，python版本3.5，torchtext0.2.3。报的错和楼上的一样，一直没法解决。麻烦作者告知一下。

**Comment by xugege0523** [comment]
> 能也发我一份数据吗，谢谢! @AtmaHou 邮箱[420097885@qq.com](mailto:420097885@qq.com)
你的问题是torchtext版本，改为0.1.1即可。

**Comment by AtmaHou** [comment]
数据已发，感谢回答

**Comment by daiw10** [comment]
能发我一份数据吗，谢谢! @AtmaHou daiw01518385@163.com

**Comment by AtmaHou** [comment]
> 能发我一份数据吗，谢谢! @AtmaHou [daiw01518385@163.com](mailto:daiw01518385@163.com)

已发

**Comment by daiw10** [comment]
非常感谢 @AtmaHou  还有一个问题，如果想做中文的类似问句生成，有什么好的数据集推荐么

**Comment by AtmaHou** [comment]
> 非常感谢 @AtmaHou 还有一个问题，如果想做中文的类似问句生成，有什么好的数据集推荐么

中文的不清楚，我知道大概有一个CQA数据，貌似是爬的百度知道的问答，我这里没有，你可以找找。

**Comment by daiw10** [comment]
@AtmaHou 了解 谢谢

**Comment by daiw10** [comment]
@AtmaHou  抱歉可能理解有误，想咨询的是中文有类似ATIS这样的数据做问题扩充么？ 不是中文QA数据，谢谢

**Comment by AtmaHou** [comment]
> @AtmaHou 抱歉可能理解有误，想咨询的是中文有类似ATIS这样的数据做问题扩充么？ 不是中文QA数据，谢谢

哦哦，这个我比较确定暂时是没有的~

**Comment by AtmaHou** [comment]
> @AtmaHou 抱歉可能理解有误，想咨询的是中文有类似ATIS这样的数据做问题扩充么？ 不是中文QA数据，谢谢

你想要的是“任务型对话数据集”，关于这个我做过一个survey，应该是全的，需要的话你可以看一下：

https://github.com/AtmaHou/Task-Oriented-Dialogue-Dataset-Survey​



其中， 完全满足你要求的中文数据只有灵犀数据，可惜这个数据并不开源。

还有一个类似的可能会满足你要求，是今年ALC发布的那个中文医疗对话数据，我的survey里也包含了，你可以看看。

**Comment by monicatao** [comment]
> _No description provided._



> 您好，我的环境：python3.5，pytorch 0.3.1，模式为intent-slot；
> 但是在第三步python3 run_onmt_generation.py -t atis_labeled -f
> 还是遇到了问题，报错如下：
> b'Preparing training ...\n'
> b'Building Training...\n'
> b'Building Vocab...\n'
> b'Building Valid...\n'
> b'Saving train/valid/fields\n'
> b'Traceback (most recent call last):\n'
> b' File "./OpenNMT/preprocess.py", line 94, in \n'
> b' main()\n'
> b' File "./OpenNMT/preprocess.py", line 89, in main\n'
> b" torch.save(train, open(opt.save_data + '.train.pt', 'wb'))\n"
> b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 135, in save\n'
> b' return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))\n'
> b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 117, in _with_file_like\n'
> b' return body(f)\n'
> b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 135, in \n'
> b' return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))\n'
> b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 198, in _save\n'
> b' pickler.dump(obj)\n'
> b"AttributeError: Can't pickle local object 'ONMTDataset.**init**..filter_pred'\n"
> Traceback (most recent call last):
> File "run_onmt_generation.py", line 278, in 
> main()
> File "run_onmt_generation.py", line 268, in main
> call_onmt('prepare_data' + TASK_NAME + cluster_method + str(split_rate) + pair_mod_str + no_index_str + no_filtering_str, param_config['prepare_data'])
> File "run_onmt_generation.py", line 225, in call_onmt
> raise RuntimeError
> RuntimeError
> 
> 本来不想麻烦您的，但是确实三天没有解决了；多谢！

你好，请问你是用自己电脑跑还是其他GPU？大概要跑多久呢？我现在已经在跑了，但是不知道要多久，只是想有一个大概的timeline.感谢！

**Comment by ZhenwenZhang** [comment]
您好！能发我一份您论文中使用的数据吗？谢谢! @AtmaHou  
Email:gstszzw@gmail.com

**Comment by AtmaHou** [comment]
> 您好！能发我一份您论文中使用的数据吗？谢谢! @AtmaHou
> Email:[gstszzw@gmail.com](mailto:gstszzw@gmail.com)

已发

**Comment by jiaozhusos** [comment]
你好，可以提供下数据吗 ,谢谢。@AtmaHou
email: zhaoxuejiaotyut@126.com

**Comment by liangxiao** [comment]
> 您好，我的环境：python3.5，pytorch 0.3.1，模式为intent-slot；
> 但是在第三步python3 run_onmt_generation.py -t atis_labeled -f
> 还是遇到了问题，报错如下：
> b'Preparing training ...\n'
> b'Building Training...\n'
> b'Building Vocab...\n'
> b'Building Valid...\n'
> b'Saving train/valid/fields\n'
> b'Traceback (most recent call last):\n'
> b' File "./OpenNMT/preprocess.py", line 94, in \n'
> b' main()\n'
> b' File "./OpenNMT/preprocess.py", line 89, in main\n'
> b" torch.save(train, open(opt.save_data + '.train.pt', 'wb'))\n"
> b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 135, in save\n'
> b' return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))\n'
> b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 117, in _with_file_like\n'
> b' return body(f)\n'
> b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 135, in \n'
> b' return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))\n'
> b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 198, in _save\n'
> b' pickler.dump(obj)\n'
> b"AttributeError: Can't pickle local object 'ONMTDataset.**init**..filter_pred'\n"
> Traceback (most recent call last):
> File "run_onmt_generation.py", line 278, in
> main()
> File "run_onmt_generation.py", line 268, in main
> call_onmt('prepare_data' + TASK_NAME + cluster_method + str(split_rate) + pair_mod_str + no_index_str + no_filtering_str, param_config['prepare_data'])
> File "run_onmt_generation.py", line 225, in call_onmt
> raise RuntimeError
> RuntimeError
> 
> 本来不想麻烦您的，但是确实三天没有解决了；多谢！

碰到同样问题，原因是torchtext的版本问题，换成0.1.1版本，问题解决

**Comment by AtmaHou** [comment]
> > 您好，我的环境：python3.5，pytorch 0.3.1，模式为intent-slot；
> > 但是在第三步python3 run_onmt_generation.py -t atis_labeled -f
> > 还是遇到了问题，报错如下：
> > b'Preparing training ...\n'
> > b'Building Training...\n'
> > b'Building Vocab...\n'
> > b'Building Valid...\n'
> > b'Saving train/valid/fields\n'
> > b'Traceback (most recent call last):\n'
> > b' File "./OpenNMT/preprocess.py", line 94, in \n'
> > b' main()\n'
> > b' File "./OpenNMT/preprocess.py", line 89, in main\n'
> > b" torch.save(train, open(opt.save_data + '.train.pt', 'wb'))\n"
> > b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 135, in save\n'
> > b' return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))\n'
> > b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 117, in _with_file_like\n'
> > b' return body(f)\n'
> > b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 135, in \n'
> > b' return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))\n'
> > b' File "/Users/a1/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 198, in _save\n'
> > b' pickler.dump(obj)\n'
> > b"AttributeError: Can't pickle local object 'ONMTDataset.**init**..filter_pred'\n"
> > Traceback (most recent call last):
> > File "run_onmt_generation.py", line 278, in
> > main()
> > File "run_onmt_generation.py", line 268, in main
> > call_onmt('prepare_data' + TASK_NAME + cluster_method + str(split_rate) + pair_mod_str + no_index_str + no_filtering_str, param_config['prepare_data'])
> > File "run_onmt_generation.py", line 225, in call_onmt
> > raise RuntimeError
> > RuntimeError
> > 本来不想麻烦您的，但是确实三天没有解决了；多谢！
> 
> 碰到同样问题，原因是torchtext的版本问题，换成0.1.1版本，问题解决

Thanks a lot!

**Comment by wodejiafeiyu** [comment]
哈喽，可以提供下数据吗 ,谢谢！@AtmaHou
email: 10418743@qq.com

**Comment by AtmaHou** [comment]
> 哈喽，可以提供下数据吗 ,谢谢！@AtmaHou
> email: [10418743@qq.com](mailto:10418743@qq.com)

Data is already included in the rep: root/Data/
