### ISSUE TITLE
Can't run the code follow the instructions

### ISSUE THREAD

**Issue by whoami0022** [AtmaHou/Seq2SeqDataAugmentationForLU#4]
Can't run the code follow the instructions, is it possible to fix it? Thanks

**Comment by AtmaHou** [comment]
Maybe having a look at the solved issue will help?

**Comment by yun97** [comment]
Could you please provide the whole data?

**Comment by rjzevallos** [comment]
Hii, I have tried run this code but I can't do it. please can you upload the data folder?

**Comment by AtmaHou** [comment]
> Hii, I have tried run this code but I can't do it. please can you upload the data folder?

https://github.com/AtmaHou/Seq2SeqDataAugmentationForLU/tree/master/Data

This is folder for all the data used in experiments. 
(Notice that it is still not associated with the path in code, you still need to set it.)

**Comment by rjzevallos** [comment]
But Data folder contains only conll files, so these files are the initial dataset? How did you get theses conll files?

**Comment by AtmaHou** [comment]
> But Data folder contains only conll files, so these files are the initial dataset? How did you get theses conll files?

ok, I understand what you mean now.
From the code point of view, I should have read the conll data directly.

https://github.com/AtmaHou/Seq2SeqDataAugmentationForLU/blob/46376b4c243f7087316d7fc964b7cab90c924783/run_clustering.py#L29

What is the error you encountered?
